name: 'Run'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: |
          ./gradlew build -Pversion1.21.2-pre3
          ./gradlew run -Pversion1.21.2-pre3
          git checkout --orphan temp
          cp -r "generated/${{ needs.check.outputs.id }}/"* .
          git clean -fdX
          rm -r .github/ src/ .gitignore .gitattributes build.gradle gradle.properties gradlew gradlew.bat settings.gradle
          git add .
          git commit -m "🚀 Update generated contents for ${{ needs.check.outputs.id }}"
          git tag -f "${{ needs.check.outputs.id }}"
          git push origin "${{ needs.check.outputs.id }}" --force
