name: 'Run'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: |
          bash extract.sh ${{ inputs.version }}
          git checkout --orphan temp
          cp -r "generated/${{ inputs.version }}/"* .
          git clean -fdX
          rm -r .github/ src/ extract.sh .gitignore
          git add .
          git commit -m "🚀 Update generated contents for ${{ inputs.version }}"
          git tag -f "${{ inputs.version }}"
          git push origin "${{ inputs.version }}" --force
