name: 'Tick'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.check.outputs.id }}
    steps:
      - id: check
        name: Check for Minecraft updates
        uses: ByMartrixX/minecraft-update-check-action@v0
        with:
          version-manifest-url: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
          cache-base-key: 'mc-manifest-'

  update:
    needs: check
    if: ${{ needs.check.outputs.id != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@v2
      - run: |
          ./gradlew build -Pversion1.21.2-pre3
          ./gradlew run -Pversion1.21.2-pre3
          git checkout --orphan temp
          cp -r "generated/${{ needs.check.outputs.id }}/"* .
          git clean -fdX
          rm -r .github/ src/ .gitignore .gitattributes build.gradle gradle.properties gradlew gradlew.bat settings.gradle
          git add .
          git commit -m "🚀 Update generated contents for ${{ needs.check.outputs.id }}"
          git tag -f "${{ needs.check.outputs.id }}"
          git push origin "${{ needs.check.outputs.id }}" --force
